FORMAT: 1A
HOST: https://gotacomponentapi.docs.apiary.io/#

# GOTA Component MS API
The GOTA `Component` Microservice API description part of the TOMAS training.

`Components` are building blocks which you can use to break down projects into smaller parts.

A part of the `Component` data structure is shared between the `Component` definition itself and the `Create a Component` action, it was separated into a `Component Base` data structure in the `Data Structures` API Blueprint Section. Doing so enables us to reuse it as a base-type of other attribute definitions.

## GOTA System API Blueprint References
+ [Example: References to other Microservices]()

## Component  [/api/v1/component{id}]
A component contains information such as ID, Created Date, Name, Description, Owner and Default Assignee.

+ Parameters
    + id (string)

        The ID of the desired component.

+ Attributes (Component Base)
    + id: `Component Identifier` (string, required)
    + created_date: `Component date creation` (string, optional)
    + name: `Component Name` (string, required)

### Get Component [GET]
Retrives the Component with the given ID.

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 200 (application/json)
    + Attributes (Component)

### Edit Component [PUT]
Edit a Component with the given ID.

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 200 (application/json)
    + Attributes (Component)

### Disable Component  [POST]
Disable a Component with the given ID.

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 200 (application/json)

### Delete Component [DELETE]
Delete a Component with the given ID.

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 200 (application/json)


## Components [/api/v1/components{?limit}]

+ Attributes (array[Component])

### List all Components [GET]
Returns a list of your Components.

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and XXX items.

        + Default: `10`

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 200 (application/json)
    + Attributes (Components)

### Create a Component [POST]
Creates a new Component.

+ Attributes (Component Base)

+ Request (text/plain)

    + Headers

            api-key: ac108161-d3a5-427d-b814-ff977728395b

+ Response 201 (application/json)
    + Attributes (Component)

# Data Structures

## Component Base (object)
+ description: `Component Description` (string, optional)
+ owner: `Component Owner` (string, optional)
+ default_assignee: `Component Default Assignee` (string, optional)

## Response Metadata (object)
- error (boolean, required)
- message: `Outcome of transaction` (string, optional)